server:
  port: 9901 # 端口
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID # 防止cookie冲突
oauth2-server-url: http://localhost:9900
spring:
  application:
    name: oauth2-client
  security: # oauth-server
    oauth2:
      client:
        client-id: admin
        client-secret: abc
        user-authorization-uri: ${oauth2-server-url}/oauth/authorize
        access-token-uri: ${oauth2-server-url}/oauth/token
      resource:
        jwt:
          key-uri: ${oauth2-server-url}/oauth/token_key