# Eureka注册中心集群配置文件,通过两个注册中心互相注册，搭建了注册中心的双节点集群
server:
  port: 8003
spring:
  application:
    name: eureka-server-rep2
eureka:
  instance:
    hostname: replica1
  client:
    service-url:
      defaultZone: http://replica1:8002/eureka/ #注册到另一个注册中心
    fetch-registry: true
    register-with-eureka: true