# Eureka注册中心集群配置文件
server:
  port: 8002
spring:
  application:
    name: eureka-server-rep1
eureka:
  instance:
    hostname: replica1
  client:
    service-url:
      defaultZone: http://replica2:8003/eureka/ #注册到另一个注册中心
    fetch-registry: true
    register-with-eureka: true